---
- name: copy files to destination
  hosts: all
  tasks:
  #- name: remote copy file to another server
  #    copy:
  #      src: /agents/UEMSLinuxAgent.zip
  #      dest: /tmp/UEMSLinuxAgent.zip

    - name: Extract zipped file into destination
      ansible.builtin.unarchive:
       src: /tmp/UEMSLinuxAgent.zip
       dest: /tmp
       remote_src: yes
       
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
       path: /tmp/UEMS_LinuxAgent.bin
       mode: '0777'

    - name: Run command
      expect:
       command: /tmp/UEMS_LinuxAgent.bin
       responses:
        Do you want to uninstall .*: "y"
      timeout: 60
      args:
       chdir: /tmp/
       register: results
    - debug:
      var: results.stdout
