---
- name: copy files to destination
  hosts: all
  tasks:
    - name: remote copy file to another server
      get_url:
       url: https://ruh-sat-center.salam.sa/pulp/content/Default_Organization/Library/custom/UEMS/UEMSLinuxAgent_zip/UEMSLinuxAgent.zip
       dest: /tmp/UEMSLinuxAgent.zip
    
    - name: Extract zipped file into destination
      ansible.builtin.unarchive:
       src: /tmp/UEMSLinuxAgent.zip
       dest: /tmp
       remote_src: yes
       
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
       path: /tmp/UEMS_LinuxAgent.bin
       mode: '0777'

    - name: Run command
      expect:
       command: /tmp/UEMS_LinuxAgent.bin
       responses:
        Do you want to uninstall .*: "y"
      timeout: 60
      args:
       chdir: /tmp/
      register: results
    - debug:
       var: results.stdout
